#user  nobody;
worker_processes 1;

events {
    worker_connections 1024;
}

http {

    include mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;
    client_max_body_size 20M;

    # -----------------------------
    # NeuralWeb
    # -----------------------------
    server {
        listen 80;
        server_name neuralweb-app.ioak.io;

        location / {
            proxy_pass http://localhost:7004;
        }
    }

    # -----------------------------
    # Service
    # -----------------------------
    server {
        listen 80;
        server_name service.ioak.io;

        location / {
            proxy_pass http://127.0.0.1:8000;
        }
    }

    # -----------------------------
    # Keycloak
    # -----------------------------
    server {
        listen 80;
        server_name keycloak.ioak.io;

        location / {
            proxy_pass http://127.0.0.1:8080;
        }
    }

    # -----------------------------
    # Sparkles
    # -----------------------------
    server {
        listen 80;
        server_name sparkles.ioak.io;

        location / {
            proxy_pass http://localhost:2300;
        }
    }

    # -----------------------------
    # Contacts
    # -----------------------------
    server {
        listen 80;
        server_name contacts.ioak.io;

        location / {
            proxy_pass http://localhost:7000;
        }
    }

    # -----------------------------
    # API
    # -----------------------------
    server {
        listen 80;
        server_name api.ioak.io;

        location / {
            proxy_pass http://localhost:8005;
        }
    }

}